/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnonymFormContainer: typeof import('./src/components/AnonymFormContainer.vue')['default']
    Button: typeof import('primevue/button')['default']
    CalendarCell: typeof import('./src/components/calendar/CalendarCell.vue')['default']
    CalendarTemplate: typeof import('./src/components/calendar/CalendarTemplate.vue')['default']
    Chip: typeof import('primevue/chip')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DrawerTemplate: typeof import('./src/components/DrawerTemplate.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Form: typeof import('@primevue/forms/form')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MonthCalendar: typeof import('./src/components/calendar/MonthCalendar.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    ThemeToggleSwitch: typeof import('./src/components/ThemeToggleSwitch.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    WeekCalendar: typeof import('./src/components/calendar/WeekCalendar.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
